#!/bin/bash
# Make a gnirehtet release.
#
# Put your keystore properties into ~/.gradle/gradle.properties
# (check app/build.gradle)

set -e # fail on error

GRADLE=${GRADLE:-./gradlew} # set value ./gradlew if not set
DIST=dist
TARGET_DIR_RUST_LINUX=gnirehtet-rust-linux64
TARGET_DIR_RUST_WIN=gnirehtet-rust-win64

version=$(git describe --tags --always)
TARGET_RUST_LINUX="$TARGET_DIR_RUST_LINUX-$version".zip
TARGET_RUST_WIN="$TARGET_DIR_RUST_WIN-$version".zip

"$GRADLE" checkAll releaseAll releaseWindows

rm -rf "$DIST"

for dir in "$TARGET_DIR_RUST_LINUX" "$TARGET_DIR_RUST_WIN"
do
    mkdir -p "$DIST/$dir"
    cp app/build/outputs/apk/release/gnirehtet-release.apk "$DIST/$dir"/gnirehtet.apk
done

cp relay/target/release/gnirehtet "$DIST/$TARGET_DIR_RUST_LINUX"/
strip "$DIST/$TARGET_DIR_RUST_LINUX"/gnirehtet  # remove symbols for smaller binary
cp relay/target/x86_64-pc-windows-gnu/release/gnirehtet.exe \
   relay/scripts/gnirehtet-run.cmd \
   "$DIST/$TARGET_DIR_RUST_WIN"/

cd "$DIST"
zip -r "$TARGET_RUST_LINUX" "$TARGET_DIR_RUST_LINUX"
zip -r "$TARGET_RUST_WIN" "$TARGET_DIR_RUST_WIN"
sha256sum "$TARGET_RUST_LINUX" "$TARGET_RUST_WIN" > SHA256SUMS.txt
